name: Release
on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version:  22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Run e2e tests
        uses: cypress-io/github-action@v3

      - name: Compress Github release files
        run: |
          zip -r h5p-standalone-release.zip dist/ README.md

      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: h5p-standalone-release
          path: h5p-standalone-release.zip
